const data = [
    {
        id: 1,
        name: "Paracetamol",
        info: "Paracetamol is a common painkiller used to treat aches and pain. It can also be used to reduce a high temperature.",
        image: "https://www.netmeds.com/images/product-v1/600x600/837692/dolo_1000_tablet_10s_566310_0_0.jpg",
        price: "50",
    },
    {
        id: 2,
        name: "Ibuprofen",
        info: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used for relieving pain, helping with fever, and reducing inflammation.",
        image: "https://www.netmeds.com/images/product-v1/600x600/379177/brufen_200mg_tablet_15s_0_1.jpg",
        price: "75",
    },
    {
        id: 3,
        name: "Amoxicillin",
        info: "Amoxicillin is an antibiotic used to treat a number of bacterial infections. It is a penicillin-type antibiotic.",
        image: "https://www.netmeds.com/images/product-v1/600x600/380216/verclav_625mg_tablet_10s_434024_0_0.jpg",
        price: "120",
    },
    {
        id: 4,
        name: "Cetirizine",
        info: "Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.",
        image: "https://www.netmeds.com/images/product-v1/600x600/399531/cetzine_syrup_60ml_47636_0_1.jpg",
        price: "60",
    },
    {
        id: 5,
        name: "Metformin",
        info: "Metformin is a medication used to treat type 2 diabetes. It helps control blood sugar levels.",
        image: "https://www.netmeds.com/images/product-v1/600x600/53613/glycomet_sr_500mg_tablet_20s_0_1.jpg",
        price: "150",
    },
    {
        id: 6,
        name: "Aspirin",
        info: "Aspirin is used to reduce fever and relieve mild to moderate pain from conditions such as muscle aches, toothaches, common cold, and headaches.",
        image: "https://www.netmeds.com/images/product-v1/600x600/9799/ecosprin_av_75_20mg_capsule_10s_31495_0_1.jpg",
        price: "40",
    },
    {
        id: 7,
        name: "Lisinopril",
        info: "Lisinopril is used to treat high blood pressure and heart failure. It is also used to improve survival after a heart attack.",
        image: "https://www.netmeds.com/images/product-v1/600x600/370050/lipril_2_5mg_tablet_15s_0_1.jpg",
        price: "200",
    },
    {
        id: 8,
        name: "Atorvastatin",
        info: "Atorvastatin is used to improve cholesterol levels and decrease your risk for a heart attack and stroke.",
        image: "https://www.netmeds.com/images/product-v1/600x600/861357/atorva_10mg_tablet_15s_98809_0_1.jpg",
        price: "180",
    },
    {
        id: 9,
        name: "Omeprazole",
        info: "Omeprazole is used to treat certain stomach and esophagus problems (such as acid reflux, ulcers). It works by decreasing the amount of acid your stomach makes.",
        image: "https://www.netmeds.com/images/product-v1/600x600/333947/omez_insta_20mg_mint_flavour_powder_5_9gm_40937_0_3.jpg",
        price: "90",
    },
    {
        id: 10,
        name: "Simvastatin",
        info: "Simvastatin is used to lower cholesterol and triglycerides in the blood. It may reduce the risk of heart attack, stroke, and related health conditions.",
        image: "https://www.netmeds.com/images/product-v1/600x600/333606/simvotin_10mg_tablet_10s_40870_0_1.jpg",
        price: "160",
    },
    {
        id: 11,
        name: "Levothyroxine",
        info: "Levothyroxine is used to treat an underactive thyroid (hypothyroidism). It replaces or provides more thyroid hormone, which is normally produced by the thyroid gland.",
        image: "https://www.netmeds.com/images/product-v1/600x600/822526/euthyrox_75mcg_tablet_100s_0_0.jpg",
        price: "130",
    },
    {
        id: 12,
        name: "Amlodipine",
        info: "Amlodipine is used to treat high blood pressure and chest pain (angina). Lowering high blood pressure helps prevent strokes, heart attacks, and kidney problems.",
        image: "https://www.netmeds.com/images/product-v1/600x600/412509/stamlo_2_5mg_tablet_30s_0_1.jpg",
        price: "110",
    },
    {
        id: 13,
        name: "Metoprolol",
        info: "Metoprolol is used to treat high blood pressure, chest pain (angina), and heart failure. It is also used to improve survival after a heart attack.",
        image: "https://www.netmeds.com/images/product-v1/600x600/49026/metocard_xl_25mg_tablet_10s_35726_0_1.jpg",
        price: "140",
    },
    {
        id: 14,
        name: "Losartan",
        info: "Losartan is used to treat high blood pressure and to help protect the kidneys from damage due to diabetes.",
        image: "https://www.netmeds.com/images/product-v1/600x600/44621/losar_25mg_tablet_15s_0_0.jpg",
        price: "170",
    },
    {
        id: 15,
        name: "Gabapentin",
        info: "Gabapentin is used to help control seizures in people with epilepsy. It is also used to relieve nerve pain following shingles (a painful rash due to herpes zoster infection).",
        image: "https://www.netmeds.com/images/product-v1/600x600/43860/gabantin_100mg_capsule_10s_35097_0_3.jpg",
        price: "190",
    },
    {
        id: 16,
        name: "Hydrochlorothiazide",
        info: "Hydrochlorothiazide is used to treat high blood pressure and fluid retention (edema). It helps prevent strokes, heart attacks, and kidney problems.",
        image: "https://www.netmeds.com/images/product-v1/600x600/360969/telma_h_40mg_tablet_15_s_0.jpg",
        price: "80",
    },
    {
        id: 17,
        name: "Furosemide",
        info: "Furosemide is a diuretic (water pill) used to reduce extra fluid in the body (edema) caused by conditions such as heart failure, liver disease, and kidney disease.",
        image: "https://www.netmeds.com/images/product-v1/600x600/364331/furoped_pineapple_flavour_oral_solution_30ml_107799_0_1.jpg",
        price: "90",
    },
    {
        id: 18,
        name: "Clopidogrel",
        info: "Clopidogrel is used to prevent heart attacks and strokes in persons with heart disease (recent heart attack), recent stroke, or blood circulation disease (peripheral vascular disease).",
        image: "https://www.netmeds.com/images/product-v1/600x600/404318/clopilet_75mg_tablet_15s_48059_0_1.jpg",
        price: "210",
    },
    {
        id: 19,
        name: "Montelukast",
        info: "Montelukast is used to prevent wheezing and shortness of breath caused by asthma and decrease the number of asthma attacks.",
        image: "https://www.netmeds.com/images/product-v1/600x600/325193/montek_10mg_tablet_10s_0_0.jpg",
        price: "150",
    },
    {
        id: 20,
        name: "Prednisone",
        info: "Prednisone is used to treat conditions such as arthritis, blood disorders, breathing problems, severe allergies, skin diseases, cancer, eye problems, and immune system disorders.",
        image: "https://www.netmeds.com/images/product-v1/600x600/964718/paedisone_m_cream_15gm_0_1.jpg",
        price: "130",
    },
    {
        id: 21,
        name: "Warfarin",
        info: "Warfarin is used to treat blood clots (such as in deep vein thrombosis-DVT or pulmonary embolus-PE) and/or to prevent new clots from forming in your body.",
        image: "https://www.netmeds.com/images/product-v1/600x600/899921/warf_5mg_tablet_30s_0_0.jpg",
        price: "100",
    },
    {
        id: 22,
        name: "Tramadol",
        info: "Tramadol is used to help relieve moderate to moderately severe pain. It is similar to opioid (narcotic) analgesics.",
        image: "https://www.netmeds.com/images/product-v1/600x600/948242/biotram_injection_2ml_0_0.jpg",
        price: "120",
    },
    {
        id: 23,
        name: "Alprazolam",
        info: "Alprazolam is used to treat anxiety and panic disorders. It belongs to a class of medications called benzodiazepines which act on the brain and nerves (central nervous system) to produce a calming effect.",
        image: "https://www.netmeds.com/images/product-v1/600x600/989769/alpradream_tablet_10s_0_0.jpg",
        price: "140",
    },
    {
        id: 24,
        name: "Clonazepam",
        info: "Clonazepam is used to prevent and control seizures. This medication is known as an anticonvulsant or antiepileptic drug.",
        image: "https://www.netmeds.com/images/product-v1/600x600/995706/clotas_md_0_25_tablet_15s_408329_0_3.jpg",
        price: "160",
    },
    {
        id: 25,
        name: "Fluoxetine",
        info: "Fluoxetine is used to treat depression, panic attacks, obsessive compulsive disorder (OCD), a certain eating disorder (bulimia), and a severe form of premenstrual syndrome (premenstrual dysphoric disorder).",
        image: "https://www.netmeds.com/images/product-v1/600x600/43824/fludac_20mg_capsule_15s_35090_0_2.jpg",
        price: "180",
    },
    {
        id: 26,
        name: "Citalopram",
        info: "Citalopram is used to treat depression. It may improve your energy level and feelings of well-being.",
        image: "https://www.netmeds.com/images/product-v1/600x600/364331/furoped_pineapple_flavour_oral_solution_30ml_107799_0_1.jpg",
        price: "170",
    },
    {
        id: 27,
        name: "Paracetamol",
        info: "Paracetamol is a common painkiller used to treat aches and pain. It can also be used to reduce a high temperature.",
        image: "https://www.netmeds.com/images/product-v1/600x600/837692/dolo_1000_tablet_10s_566310_0_0.jpg",
        price: "50",
    },
    {
        id: 28,
        name: "Ibuprofen",
        info: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used for relieving pain, helping with fever, and reducing inflammation.",
        image: "https://www.netmeds.com/images/product-v1/600x600/379177/brufen_200mg_tablet_15s_0_1.jpg",
        price: "75",
    },
    {
        id: 29,
        name: "Amoxicillin",
        info: "Amoxicillin is an antibiotic used to treat a number of bacterial infections. It is a penicillin-type antibiotic.",
        image: "https://www.netmeds.com/images/product-v1/600x600/380216/verclav_625mg_tablet_10s_434024_0_0.jpg",
        price: "120",
    },
    {
        id: 30,
        name: "Cetirizine",
        info: "Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.",
        image: "https://www.netmeds.com/images/product-v1/600x600/399531/cetzine_syrup_60ml_47636_0_1.jpg",
        price: "60",
    },
    {
        id: 31,
        name: "Metformin",
        info: "Metformin is a medication used to treat type 2 diabetes. It helps control blood sugar levels.",
        image: "https://www.netmeds.com/images/product-v1/600x600/53613/glycomet_sr_500mg_tablet_20s_0_1.jpg",
        price: "150",
    },
    {
        id: 32,
        name: "Aspirin",
        info: "Aspirin is used to reduce fever and relieve mild to moderate pain from conditions such as muscle aches, toothaches, common cold, and headaches.",
        image: "https://www.netmeds.com/images/product-v1/600x600/9799/ecosprin_av_75_20mg_capsule_10s_31495_0_1.jpg",
        price: "40",
    },
    {
        id: 33,
        name: "Lisinopril",
        info: "Lisinopril is used to treat high blood pressure and heart failure. It is also used to improve survival after a heart attack.",
        image: "https://www.netmeds.com/images/product-v1/600x600/370050/lipril_2_5mg_tablet_15s_0_1.jpg",
        price: "200",
    },
    {
        id: 34,
        name: "Atorvastatin",
        info: "Atorvastatin is used to improve cholesterol levels and decrease your risk for a heart attack and stroke.",
        image: "https://www.netmeds.com/images/product-v1/600x600/861357/atorva_10mg_tablet_15s_98809_0_1.jpg",
        price: "180",
    },
    {
        id: 35,
        name: "Omeprazole",
        info: "Omeprazole is used to treat certain stomach and esophagus problems (such as acid reflux, ulcers). It works by decreasing the amount of acid your stomach makes.",
        image: "https://www.netmeds.com/images/product-v1/600x600/333947/omez_insta_20mg_mint_flavour_powder_5_9gm_40937_0_3.jpg",
        price: "90",
    },
    {
        id: 36,
        name: "Simvastatin",
        info: "Simvastatin is used to lower cholesterol and triglycerides in the blood. It may reduce the risk of heart attack, stroke, and related health conditions.",
        image: "https://www.netmeds.com/images/product-v1/600x600/333606/simvotin_10mg_tablet_10s_40870_0_1.jpg",
        price: "160",
    },
    {
        id: 37,
        name: "Levothyroxine",
        info: "Levothyroxine is used to treat an underactive thyroid (hypothyroidism). It replaces or provides more thyroid hormone, which is normally produced by the thyroid gland.",
        image: "https://www.netmeds.com/images/product-v1/600x600/822526/euthyrox_75mcg_tablet_100s_0_0.jpg",
        price: "130",
    },
    {
        id: 38,
        name: "Amlodipine",
        info: "Amlodipine is used to treat high blood pressure and chest pain (angina). Lowering high blood pressure helps prevent strokes, heart attacks, and kidney problems.",
        image: "https://www.netmeds.com/images/product-v1/600x600/412509/stamlo_2_5mg_tablet_30s_0_1.jpg",
        price: "110",
    },
    {
        id: 39,
        name: "Metoprolol",
        info: "Metoprolol is used to treat high blood pressure, chest pain (angina), and heart failure. It is also used to improve survival after a heart attack.",
        image: "https://www.netmeds.com/images/product-v1/600x600/49026/metocard_xl_25mg_tablet_10s_35726_0_1.jpg",
        price: "140",
    },
    {
        id: 40,
        name: "Losartan",
        info: "Losartan is used to treat high blood pressure and to help protect the kidneys from damage due to diabetes.",
        image: "https://www.netmeds.com/images/product-v1/600x600/44621/losar_25mg_tablet_15s_0_0.jpg",
        price: "170",
    },
    {
        id: 41,
        name: "Gabapentin",
        info: "Gabapentin is used to help control seizures in people with epilepsy. It is also used to relieve nerve pain following shingles (a painful rash due to herpes zoster infection).",
        image: "https://www.netmeds.com/images/product-v1/600x600/43860/gabantin_100mg_capsule_10s_35097_0_3.jpg",
        price: "190",
    },
    {
        id: 42,
        name: "Hydrochlorothiazide",
        info: "Hydrochlorothiazide is used to treat high blood pressure and fluid retention (edema). It helps prevent strokes, heart attacks, and kidney problems.",
        image: "https://www.netmeds.com/images/product-v1/600x600/360969/telma_h_40mg_tablet_15_s_0.jpg",
        price: "80",
    },
    {
        id: 43,
        name: "Furosemide",
        info: "Furosemide is a diuretic (water pill) used to reduce extra fluid in the body (edema) caused by conditions such as heart failure, liver disease, and kidney disease.",
        image: "https://www.netmeds.com/images/product-v1/600x600/364331/furoped_pineapple_flavour_oral_solution_30ml_107799_0_1.jpg",
        price: "90",
    },
    {
        id: 44,
        name: "Clopidogrel",
        info: "Clopidogrel is used to prevent heart attacks and strokes in persons with heart disease (recent heart attack), recent stroke, or blood circulation disease (peripheral vascular disease).",
        image: "https://www.netmeds.com/images/product-v1/600x600/404318/clopilet_75mg_tablet_15s_48059_0_1.jpg",
        price: "210",
    },
    {
        id: 45,
        name: "Montelukast",
        info: "Montelukast is used to prevent wheezing and shortness of breath caused by asthma and decrease the number of asthma attacks.",
        image: "https://www.netmeds.com/images/product-v1/600x600/325193/montek_10mg_tablet_10s_0_0.jpg",
        price: "150",
    },
    {
        id: 46,
        name: "Prednisone",
        info: "Prednisone is used to treat conditions such as arthritis, blood disorders, breathing problems, severe allergies, skin diseases, cancer, eye problems, and immune system disorders.",
        image: "https://www.netmeds.com/images/product-v1/600x600/964718/paedisone_m_cream_15gm_0_1.jpg",
        price: "130",
    },
    {
        id: 47,
        name: "Warfarin",
        info: "Warfarin is used to treat blood clots (such as in deep vein thrombosis-DVT or pulmonary embolus-PE) and/or to prevent new clots from forming in your body.",
        image: "https://www.netmeds.com/images/product-v1/600x600/899921/warf_5mg_tablet_30s_0_0.jpg",
        price: "100",
    },
    {
        id: 48,
        name: "Tramadol",
        info: "Tramadol is used to help relieve moderate to moderately severe pain. It is similar to opioid (narcotic) analgesics.",
        image: "https://www.netmeds.com/images/product-v1/600x600/948242/biotram_injection_2ml_0_0.jpg",
        price: "120",
    },
    {
        id: 49,
        name: "Alprazolam",
        info: "Alprazolam is used to treat anxiety and panic disorders. It belongs to a class of medications called benzodiazepines which act on the brain and nerves (central nervous system) to produce a calming effect.",
        image: "https://www.netmeds.com/images/product-v1/600x600/989769/alpradream_tablet_10s_0_0.jpg",
        price: "140",
    },
    {
        id: 50,
        name: "Clonazepam",
        info: "Clonazepam is used to prevent and control seizures. This medication is known as an anticonvulsant or antiepileptic drug.",
        image: "https://www.netmeds.com/images/product-v1/600x600/995706/clotas_md_0_25_tablet_15s_408329_0_3.jpg",
        price: "160",
    },
    {
        id: 51,
        name: "Fluoxetine",
        info: "Fluoxetine is used to treat depression, panic attacks, obsessive compulsive disorder (OCD), a certain eating disorder (bulimia), and a severe form of premenstrual syndrome (premenstrual dysphoric disorder).",
        image: "https://www.netmeds.com/images/product-v1/600x600/43824/fludac_20mg_capsule_15s_35090_0_2.jpg",
        price: "180",
    },
    {
        id: 52,
        name: "Citalopram",
        info: "Citalopram is used to treat depression. It may improve your energy level and feelings of well-being.",
        image: "https://www.netmeds.com/images/product-v1/600x600/364331/furoped_pineapple_flavour_oral_solution_30ml_107799_0_1.jpg",
        price: "170",
    },
];

export default data;